build-cache
opentdf/frontend pull request #168
Opened 2023-01-05 19:22 UTC by pflynn-virtru

2023-01-06 21:41 UTC, dmihalcik-virtru requested changes

2023-01-06 21:41 UTC, dmihalcik-virtru commented on .github/workflows/build.yaml
> -      - app
This is needed to get the app version info

2023-01-06 21:41 UTC, dmihalcik-virtru commented on Dockerfile
> +COPY build/ /www/
Will this work on aarch64 (ARM platforms)?

2023-01-09 16:08 UTC, pflynn-virtru commented on .github/workflows/build.yaml
> -      - app
oh, it was just a duplicate removal.  it still blocks for it

2023-01-09 16:09 UTC, dmihalcik-virtru approved these changes

2023-01-09 16:09 UTC, dmihalcik-virtru commented on .github/workflows/build.yaml
> -      - app
OIC can you keep these alphabetized?

2023-01-09 16:12 UTC, pflynn-virtru commented on Dockerfile
> +COPY build/ /www/
The contents of `build/` are only web artifacts that are served by the http server written in Go.  The Go server is build for arm and amd. see https://github.com/opentdf/frontend/actions/runs/3858700267/jobs/6577513072#step:10:142

2023-01-09 16:18 UTC, pflynn-virtru commented on .github/workflows/build.yaml
> -      - app
done

2023-01-11 14:47 UTC, merged